#!/usr/bin/env bash
# build_installer.sh — generates a self-extracting install/upgrade script for joinery-agent.
#
# Usage:
#   ./build_installer.sh [VERSION]
#
# Output:
#   joinery-agent-installer.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${SCRIPT_DIR}/joinery-agent-installer.sh"
STAGE_DIR="$(mktemp -d)"

cleanup() { rm -rf "$STAGE_DIR"; }
trap cleanup EXIT

VERSION="${1:-dev}"
VERSION="${VERSION#v}"
echo "Building installer for joinery-agent v${VERSION}..."

# Build binary
echo "  Compiling..."
go build \
    -ldflags "-X main.version=${VERSION}" \
    -o "${STAGE_DIR}/joinery-agent" \
    "${SCRIPT_DIR}"
BINARY_SIZE="$(du -sh "${STAGE_DIR}/joinery-agent" | cut -f1)"
echo "  Build complete (${BINARY_SIZE})."

# Package payload
echo "  Packaging payload..."
cp "${SCRIPT_DIR}/install/joinery-agent.service" "${STAGE_DIR}/"
cp "${SCRIPT_DIR}/config/joinery-agent.env.example" "${STAGE_DIR}/"

tar czf "${STAGE_DIR}/payload.tar.gz" \
    -C "${STAGE_DIR}" \
    joinery-agent \
    joinery-agent.service \
    joinery-agent.env.example

PAYLOAD_B64="$(base64 < "${STAGE_DIR}/payload.tar.gz")"

# Write installer
echo "  Generating installer..."

{
cat <<'INSTALLER_HEADER'
#!/usr/bin/env bash
# joinery-agent self-extracting installer
# Generated by build_installer.sh — do not edit manually.
set -euo pipefail

INSTALLER_HEADER

echo "INSTALLER_VERSION=\"${VERSION}\""

cat <<'INSTALLER_BODY'

BINARY_PATH="/usr/local/bin/joinery-agent"
SERVICE_NAME="joinery-agent"
SERVICE_FILE="/etc/systemd/system/joinery-agent.service"
ENV_DIR="/etc/joinery-agent"
ENV_FILE="${ENV_DIR}/joinery-agent.env"
STAGE_DIR="$(mktemp -d)"

cleanup() { rm -rf "$STAGE_DIR"; }
trap cleanup EXIT

VERBOSE=false
for arg in "$@"; do
    case "$arg" in
        --verbose|-v) VERBOSE=true ;;
    esac
done

log()         { echo "$@"; }
log_verbose() { [ "$VERBOSE" = true ] && echo "  $*" || true; }
die()         { echo "ERROR: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Must be run as root."

extract_payload() {
    local payload_line
    payload_line=$(awk '/^__PAYLOAD__$/{print NR+1; exit}' "$0")
    [ -n "$payload_line" ] || die "Payload marker not found."
    local tarball="${STAGE_DIR}/payload.tar.gz"
    tail -n +"$payload_line" "$0" | base64 -d > "$tarball"
    tar xzf "$tarball" -C "$STAGE_DIR"
    rm -f "$tarball"
}

extract_payload

if [ -f "$BINARY_PATH" ]; then
    MODE="upgrade"
else
    MODE="install"
fi

log ""
log "joinery-agent installer v${INSTALLER_VERSION} (${MODE})"
log ""

if [ "$MODE" = "install" ]; then
    mkdir -p "$ENV_DIR"
    install -m 755 "${STAGE_DIR}/joinery-agent" "$BINARY_PATH"
    install -m 644 "${STAGE_DIR}/joinery-agent.service" "$SERVICE_FILE"

    if [ ! -f "$ENV_FILE" ]; then
        install -m 640 "${STAGE_DIR}/joinery-agent.env.example" "$ENV_FILE"
    fi

    systemctl daemon-reload
    systemctl enable "$SERVICE_NAME" >/dev/null
    log "Installed joinery-agent v${INSTALLER_VERSION}"
    log ""
    log "DB credentials are read automatically from Globalvars_site.php."
    log "Start the agent:"
    log "  sudo systemctl start ${SERVICE_NAME}"
    log ""
    log "If your Joinery install is not at /var/www/html/joinerytest/, edit"
    log "  ${ENV_FILE}"
    log "and set JOINERY_CONFIG to the correct Globalvars_site.php path."
    log ""
else
    cp "$BINARY_PATH" "${BINARY_PATH}.bak"
    systemctl stop "$SERVICE_NAME" 2>/dev/null || true
    install -m 755 "${STAGE_DIR}/joinery-agent" "$BINARY_PATH"
    install -m 644 "${STAGE_DIR}/joinery-agent.service" "$SERVICE_FILE"
    systemctl daemon-reload

    systemctl start "$SERVICE_NAME"
    sleep 2

    if systemctl is-active --quiet "$SERVICE_NAME"; then
        rm -f "${BINARY_PATH}.bak"
        log "Upgrade to v${INSTALLER_VERSION} successful."
    else
        log "Service failed to start — rolling back..."
        install -m 755 "${BINARY_PATH}.bak" "$BINARY_PATH"
        rm -f "${BINARY_PATH}.bak"
        systemctl start "$SERVICE_NAME" || true
        die "Upgrade failed. Check: journalctl -u ${SERVICE_NAME}"
    fi
fi

exit 0
__PAYLOAD__
INSTALLER_BODY

printf '%s\n' "$PAYLOAD_B64"

} > "$OUTPUT"

chmod +x "$OUTPUT"
echo "  Installer: $OUTPUT ($(du -sh "$OUTPUT" | cut -f1))"
echo ""
echo "Install locally:"
echo "  sudo bash joinery-agent-installer.sh --verbose"
